import{TILE_SIZE,areaFor}from"./config.js";import{World}from"./world.js";import{Player,Enemy}from"./entities.js";import{Camera}from"./camera.js";import{Input}from"./input.js";import{Renderer}from"./renderer.js";import{MiniMap}from"./minimap.js";import{findPath}from"./pathfinding.js";
export class Explore{
constructor({canvas,minimap,save,onShop,onFloor,onToast,onLoot,onGameOver}){this.canvas=canvas;this.save=save;this.onShop=onShop;this.onFloor=onFloor;this.onToast=onToast;this.onLoot=onLoot;this.onGameOver=onGameOver;this.renderer=new Renderer(canvas);this.mini=new MiniMap(minimap);this.input=new Input();this.camera=new Camera(canvas);this.running=false;this.last=0}
start(){const shop=this.save.data.floor>=this.save.data.nextShopFloor;this.world=new World().generate(shop);this.player=new Player();this.enemies=[];for(let i=0;i<5;i++)this.spawnEnemy();this.renderer.resize();this.mini.resize();this.camera.reset(TILE_SIZE,TILE_SIZE);this.input.attach(this.canvas,{onTap:p=>this.tap(p),onPan:p=>{this.camera.pan(p.dx*(this.canvas.width/this.canvas.clientWidth),p.dy*(this.canvas.height/this.canvas.clientHeight));this.camera.clamp(this.world)},onPinch:p=>{this.camera.zoomBy(p.scale);this.camera.clamp(this.world)},onDoubleTap:()=>this.camera.reset(this.player.rx*TILE_SIZE,this.player.ry*TILE_SIZE)});this.resize=()=>{this.renderer.resize();this.mini.resize()};addEventListener("resize",this.resize);this.running=true;this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}
stop(){this.running=false;this.input.detach();removeEventListener("resize",this.resize)}
spawnEnemy(){const cells=this.world.floorCells().filter(c=>Math.abs(c.x-this.player.x)+Math.abs(c.y-this.player.y)>=8&&!this.enemies.some(e=>e.x===c.x&&e.y===c.y));if(!cells.length)return;const p=cells[Math.floor(Math.random()*cells.length)],types=[["洞窟スライム","#62ce78"],["岩ゴブリン","#a08857"],["毒キノコ","#b360c9"]],type=types[Math.floor(Math.random()*types.length)];this.enemies.push(new Enemy(p.x,p.y,type[0],Math.max(1,this.save.data.floor+Math.floor(Math.random()*5)-1),type[1]))}
tap({x,y}){const r=this.canvas.getBoundingClientRect(),sx=(x-r.left)*(this.canvas.width/r.width),sy=(y-r.top)*(this.canvas.height/r.height),w=this.camera.screenToWorld(sx,sy),tile={x:Math.floor(w.x/TILE_SIZE),y:Math.floor(w.y/TILE_SIZE)};if(tile.x<0||tile.y<0||tile.x>=this.world.width||tile.y>=this.world.height||!this.world.isWalkable(tile.x,tile.y))return;this.player.setPath(findPath(this.world,this.player,tile))}
update(dt){const stepped=this.player.update(dt,5);if(stepped){for(const chest of this.world.chests)if(!chest.opened&&chest.x===this.player.x&&chest.y===this.player.y){chest.opened=true;this.onLoot?.()}if(this.world.shop&&this.player.x===this.world.shop.x&&this.player.y===this.world.shop.y){this.stop();this.onShop?.();return}if(this.player.x===this.world.exit.x&&this.player.y===this.world.exit.y){this.stop();this.onFloor?.();return}}
for(const e of this.enemies){e.patrolTimer-=dt;e.repathTimer-=dt;const d=Math.abs(e.x-this.player.x)+Math.abs(e.y-this.player.y);if(d<=5){e.alert=true;if(e.repathTimer<=0){e.setPath(findPath(this.world,e,this.player).slice(0,8));e.repathTimer=.45}}else if(d>8)e.alert=false;if(!e.alert&&e.patrolTimer<=0&&!e.path.length){const n=[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>({x:e.x+dx,y:e.y+dy})).filter(p=>this.world.isWalkable(p.x,p.y));if(n.length)e.setPath([n[Math.floor(Math.random()*n.length)]]);e.patrolTimer=1+Math.random()*2}if(e.update(dt,e.alert?2.8:1.6)&&e.x===this.player.x&&e.y===this.player.y){const loss=Math.max(3,4+Math.floor(e.level/4));this.save.update({hp:Math.max(0,this.save.data.hp-loss)});this.onToast?.(`${e.name}と接触！ HP -${loss}`);e.x=1;e.y=1;e.rx=1;e.ry=1;e.path=[];if(this.save.data.hp<=0){this.stop();this.onGameOver?.();return}}}
this.camera.follow(this.player.rx*TILE_SIZE,this.player.ry*TILE_SIZE,.08);this.camera.clamp(this.world)}
loop(t){if(!this.running)return;const dt=Math.min(.05,(t-this.last)/1000||0);this.last=t;this.update(dt);const theme=areaFor(this.save.data.floor);this.renderer.draw(this.world,this.player,this.enemies,this.camera,theme);this.mini.draw(this.world,this.player,this.enemies,theme);requestAnimationFrame(n=>this.loop(n))}
}
